Ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('product.urls')),
    path('user/', include('customer.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "Ghimire Stores Adminstration"
admin.site.site_title = "Admin"
admin.site.index_title = "Ghimire Stores"

customer/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from customer import views
from customer.forms import MyPasswordResetForm, MySetPasswordForm

app_name = 'user'
urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('reset/password/',
          auth_views.PasswordResetView.as_view(template_name='reset-password.html', form_class=MyPasswordResetForm),
          name='reset_password'
          ),
    path('reset/password/done/',
          auth_views.PasswordResetDoneView.as_view(template_name='password-reset-done.html'),
          name='password_reset_done'
          ),
    path('reset/password/confirm/<uid64>/<token>',
          auth_views.PasswordResetConfirmView.as_view(template_name='password-reset-confirm.html', form_class=MySetPasswordForm),
          name='password_reset_confirm'
          ),
    path('reset/password/complete/',
          auth_views.PasswordResetCompleteView.as_view(template_name='password-reset-complete.html'),
          name='password_reset_complete'
          ),
    path('me/', views.profile, name='profile'),
    path('update/profile/', views.update_profile, name='update_profile'),
    path('address/', views.address, name='address'),
    path('payment/', views.payment, name='payment'),
    path('change/password/', views.change_password, name='change_password'),
]

product/urls.py
from django.urls import path
from product import views

app_name = 'product'
urlpatterns = [
    path('', views.home, name='home'),
    path('products/list/', views.ProductListView.as_view(), name='product_list'),
    path('products/list/most/popular/', views.LatestProducts.as_view(), name='popular_products'),
    path('products/list/most/sold/', views.MostSoldProducts.as_view(), name='most_sold_products'),
    path('products/list/low/price/', views.LowPriceProducts.as_view(), name='low_price_products'),
    path('products/list/medium/price/', views.MediumPriceProducts.as_view(), name='medium_price_products'),
    path('products/list/high/price/', views.HighPriceProducts.as_view(), name='high_price_products'),
    path('product/details/<str:slug>/', views.ProductDetailView.as_view(), name='product_details'),
    path('add/to/cart/<str:slug>', views.add_to_cart, name='add_to_cart'),
    path('remove/from/cart/<str:slug>', views.remove_from_cart, name='remove_from_cart'),
    path('increase/quantity/<str:slug>/', views.increase_quantity, name='increase_quantity'),
    path('decrease/quantity/<str:slug>/', views.decrease_quantity, name='decrease_quantity'),
    path('cart/', views.cart, name='cart'),
    path('wishlist/', views.wishlist, name='wishlist'),
    path('checkout/', views.checkout, name='checkout'),
    path('orders/', views.orders, name='orders'),
    path('order/placed/', views.order_placed, name='order_placed'),
    path('search/', views.search, name='search'),
    path('contact/', views.contact, name='contact'),
]

templates/address.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

        <!-- My Account Start -->
        <div class="my-account">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-3">
                      <div class="nav flex-column nav-pills" role="tablist" aria-orientation="vertical">
                        <a class="nav-link" id="dashboard-nav" href="{% url 'user:profile' %}"><i class="fa fa-tachometer-alt"></i>Dashboard</a>
                        <a class="nav-link" id="orders-nav" href="{% url 'product:orders' %}"><i class="fa fa-shopping-bag"></i>Orders</a>
                        <a class="nav-link" id="payment-nav" href="{% url 'user:payment' %}"><i class="fa fa-credit-card"></i>Payment Method</a>
                        <a class="nav-link active" id="address-nav" href="{% url 'user:address' %}"><i class="fa fa-map-marker-alt"></i>Address</a>
                        <a class="nav-link" id="account-nav" href="{% url 'user:update_profile' %}"><i class="fa fa-user"></i>Update Details</a>
                        <a class="nav-link" href="{% url 'user:change_password' %}"><i class="fa fa-lock"></i>Change Password</a>
                        <a class="nav-link" href="{% url 'user:logout' %}" ><i class="fa fa-sign-out-alt"></i>Logout</a>
                      </div>
                    </div>
                    <div class="col-md-9">
                      <div class="tab-content">

                        <div class="tab-pane active" id="address-tab" role="tabpanel" aria-labelledby="address-nav">
                            <h4>Address</h4>
                            <hr>
                            <div class="row">
                              {% if not address %}
                              <div class="col-md-1"></div>
                              <div class="alert-message col-md-10">
                                <p>No address specified. Go to <b><i>Account Details</i></b> section and update your information.</p>
                              </div>
                              <div class="col-md-1"></div>
                              {% else %}
                              {% for add in address %}
                              <div class="col-md-6 profile-address">
                                  <h5>Address {{forloop.counter}}</h5>
                                  <br>
                                  <p>{{add.street}}, {{add.city}}</p>
                                  <p>{{add.district}}</p>
                                  <p>Mobile: 977-{{add.phone}}</p>
                                  <a href="{% url 'user:update_profile' %}" class="btn">Edit Address</a>
                              </div>
                              {% endfor %}
                              {% endif %}
                            </div>
                        </div>

                      </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- My Account End -->

{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Ghimire Stores | {{title}}</title>
        <meta content="width=device-width, initial-scale=1.0" name="viewport">
        <meta content="eCommerce HTML Template Free Download" name="keywords">
        <meta content="eCommerce HTML Template Free Download" name="description">

        <!-- Favicon -->
        <link href="img/favicon.ico" rel="icon">

        <!-- Google Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400|Source+Code+Pro:700,900&display=swap" rel="stylesheet">

        <!-- CSS Libraries -->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'css/slick.css' %}" rel="stylesheet">
        <link href="{% static 'css/slick-theme.css' %}" rel="stylesheet">
        <link href="{% static 'css/style.css' %}" rel="stylesheet">
    </head>

    <body>
        <!-- Nav Bar Start -->
        <div class="nav">
            <div class="container-fluid">
                <nav class="navbar navbar-expand-md bg-dark navbar-dark">
                    <a href="#" class="navbar-brand">MENU</a>
                    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                        <div class="navbar-nav mr-auto">
                            <a href="{% url 'product:home' %}" class="nav-item nav-link active">Home</a>
                            <a href="{% url 'product:product_list' %}" class="nav-item nav-link">Products</a>
                            <a href="{% url 'product:cart' %}" class="nav-item nav-link">Cart</a>
                            <a href="{% url 'product:checkout' %}" class="nav-item nav-link">Checkout</a>
                            <a href="{% url 'product:contact' %}" class="nav-item nav-link">Contact Us</a>
                        </div>
                        <div class="navbar-nav ml-auto">
                            {% if request.user.is_authenticated %}
                            <div class="nav-item dropdown">
                                <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">{{request.user.first_name|capfirst}}</a>
                                <div class="dropdown-menu">
                                    <a href="{% url 'user:profile' %}" class="dropdown-item">Profile</a>
                                    <a href="{% url 'user:logout' %}" class="dropdown-item">Logout</a>
                                </div>
                            </div>
                            {% else %}
                            <div class="nav-item dropdown">
                                <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">User Account</a>
                                <div class="dropdown-menu">
                                    <a href="{% url 'user:login' %}" class="dropdown-item">Login</a>
                                    <a href="{% url 'user:register' %}" class="dropdown-item">Register</a>
                                </div>
                            </div>
                            {% endif %}
                        </div>
                    </div>
                </nav>
            </div>
        </div>
        <!-- Nav Bar End -->

        <!-- Bottom Bar Start -->
        <div class="bottom-bar">
            <div class="container-fluid">
                <div class="row align-items-center">
                    <div class="col-md-3">
                        <div class="logo">
                            <a href="{% url 'product:home' %}">
                                <img src="{% static 'img/logo.png' %}" alt="">
                            </a>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <form class="search" method="get" action="{% url 'product:search' %}">
                            <input type="text" name="query" placeholder="Search">
                            <button><i class="fa fa-search"></i></button>
                        </form>
                    </div>
                    <div class="col-md-3">
                        <div class="user">
                            <a href="{% url 'product:wishlist' %}" class="btn wishlist">
                                <i class="fa fa-heart"></i>
                                <span>(0)</span>
                            </a>
                            <a href="{% url 'product:cart' %}" class="btn cart">
                                <i class="fa fa-shopping-cart"></i>
                                {% if request.session.cart_items_count != 0 %}
                                <span>({{ request.session.cart_items_count }})</span>
                                {% endif %}
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Bottom Bar End -->

        {% include 'message.html' %}

        <!-- Breadcrumb Start -->
        {% if title != 'Home' %}
        <div class="breadcrumb-wrap">
            <div class="container-fluid">
                <ul class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{% url 'product:home' %}">Home</a></li>
                    {% if subtitle %}
                    <li class="breadcrumb-item"><a >{{subtitle}}</a></li>
                    {% endif %}
                    <li class="breadcrumb-item active">{{title}}</li>
                </ul>
            </div>
        </div>
        {% endif %}
        <!-- Breadcrumb End -->

        {% block content %}{% endblock %}

        <!-- Footer Start -->
        <div class="footer">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-3 col-md-6">
                        <div class="footer-widget">
                            <h2>Get in Touch</h2>
                            <div class="contact-info">
                                <p><i class="fa fa-map-marker"></i>Lamachaur, Pokhara, Nepal</p>
                                <p><i class="fa fa-envelope"></i>support@ghimirestores.com</p>
                                <p><i class="fa fa-phone"></i>+977-4567890</p>
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-3 col-md-6">
                        <div class="footer-widget">
                            <h2>Company Info</h2>
                            <ul>
                                <li><a href="#">About Us</a></li>
                                <li><a href="#">Privacy Policy</a></li>
                                <li><a href="#">Terms & Condition</a></li>
                            </ul>
                        </div>
                    </div>

                    <div class="col-lg-3 col-md-6">
                        <div class="footer-widget">
                            <h2>Purchase Info</h2>
                            <ul>
                                <li><a href="#">Pyament Policy</a></li>
                                <li><a href="#">Shipping Policy</a></li>
                                <li><a href="#">Return Policy</a></li>
                            </ul>
                        </div>
                    </div>

                    <div class="col-lg-3 col-md-6">
                        <div class="footer-widget">
                            <h2>Follow Us</h2>
                            <div class="contact-info">
                                <div class="social">
                                    <a href=""><i class="fab fa-twitter"></i></a>
                                    <a href=""><i class="fab fa-facebook-f"></i></a>
                                    <a href=""><i class="fab fa-linkedin-in"></i></a>
                                    <a href=""><i class="fab fa-instagram"></i></a>
                                    <a href=""><i class="fab fa-youtube"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row payment align-items-center">
                    <div class="col-md-6">
                        <div class="payment-method">
                            <h2>We Accept:</h2>
                            <img src="{% static 'img/payment-method.png' %}" alt="" />
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="payment-security">
                            <h2>Secured By:</h2>
                            <img src="{% static 'img/godaddy.svg' %}" alt="" />
                            <img src="{% static 'img/norton.svg' %}" alt="" />
                            <img src="{% static 'img/ssl.svg' %}" alt="" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer End -->

        <!-- Footer Bottom Start -->
        <div class="footer-bottom">
            <div class="container">
                <div class="row">
                    <div class="col-md-6 copyright">
                        <p>Copyright &copy; | <a target="_blank" href="https://ghimirearun.com.np">Arun Ghimire</a> | All Rights Reserved</p>
                    </div>
                    <div class="col-md-6 template-by">
                        <p>Powered By : Ghimire Stores</p>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer Bottom End -->

        <!-- Back to Top -->
        <a href="#" class="back-to-top"><i class="fa fa-chevron-up"></i></a>

        <!-- JavaScript Libraries -->
        <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
        <script src="{% static 'js/easing.js' %}"></script>
        <script src="{% static 'js/slick.min.js' %}"></script>
        <script src="{% static 'js/main.js' %}"></script>
    </body>
</html>

templates/brand.html
{% load static %}

<!-- Brand Start -->
<div class="brand">
    <div class="container-fluid">
        <div class="brand-slider">
            <div class="brand-item"><img src="{% static 'img/brand/brand-1.png' %}" alt=""></div>
            <div class="brand-item"><img src="{% static 'img/brand/brand-2.png' %}" alt=""></div>
            <div class="brand-item"><img src="{% static 'img/brand/brand-3.png' %}" alt=""></div>
            <div class="brand-item"><img src="{% static 'img/brand/brand-4.png' %}" alt=""></div>
            <div class="brand-item"><img src="{% static 'img/brand/brand-5.png' %}" alt=""></div>
            <div class="brand-item"><img src="{% static 'img/brand/brand-6.png' %}" alt=""></div>
        </div>
    </div>
</div>
<!-- Brand End -->

templates/change-password.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

        <!-- My Account Start -->
        <div class="my-account">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-3">
                        <div class="nav flex-column nav-pills" role="tablist" aria-orientation="vertical">
                            <a class="nav-link" id="dashboard-nav" href="{% url 'user:profile' %}"><i class="fa fa-tachometer-alt"></i>Dashboard</a>
                            <a class="nav-link" id="orders-nav" href="{% url 'user:order' %}"><i class="fa fa-shopping-bag"></i>Orders</a>
                            <a class="nav-link" id="payment-nav" href="{% url 'user:update_profile' %}"><i class="fa fa-credit-card"></i>Payment Method</a>
                            <a class="nav-link" id="address-nav" href="{% url 'user:address' %}"><i class="fa fa-map-marker-alt"></i>Address</a>
                            <a class="nav-link" id="account-nav" href="{% url 'user:update_profile' %}"><i class="fa fa-user"></i>Update Details</a>
                            <a class="nav-link active" href="{% url 'user:change_password' %}"><i class="fa fa-lock"></i>Change Password</a>
                            <a class="nav-link" href="{% url 'user:logout' %}" ><i class="fa fa-sign-out-alt"></i>Logout</a>
                        </div>
                    </div>
                    <div class="col-md-9">
                      <div class="tab-content">

                        <div class="tab-pane active" id="password-tab" aria-labelledby="account-nav">
                            <h4>Password change</h4>
                            <hr>
                            <form class="row col-md-6" method="post" novalidate>
                                {% csrf_token %}
                                {% for field in change_password_form %}
                                <div class="col-md-12">
                                    {{field}}
                                </div>
                                {{field.errors|striptags}}
                                {% endfor %}
                                <div class="col-md-12">
                                    <button class="btn">Save Changes</button>
                                </div>
                            </form>
                        </div>

                      </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- My Account End -->

{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

        <!-- Login Start -->
        <div class="login">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-1"></div>
                    <div class="col-lg-4">
                        <div class="login-form">
                            <form class="row" method="post">
                                {% csrf_token %}
                                <div class="col-md-12">
                                    <label>Username</label>
                                    <input class="form-control" name="username" type="text" placeholder="Username">
                                </div>
                                <div class="col-md-12">
                                    <label>Password</label>
                                    <input class="form-control" name="password" type="password" placeholder="Password">
                                </div>
                                <div class="col-md-12 forgot-password">
                                    <a href="{% url 'user:reset_password' %}">Forgot Password?</a>
                                </div>
                                <div class="col-md-12">
                                    <button class="btn">Login</button>
                                </div>
                            </form>
                            <div class="login-register-link">New to Ghimire Stores? <a href="{% url 'user:register' %}">Create an Account</a></div>
                        </div>
                    </div>
                    <div class="col-lg-7"></div>
                </div>
            </div>
        </div>
        <!-- Login End -->

{% endblock %}

templates/order.html
{% extends 'base.html' %}
{% load static %}
{% load my_tags %}

{% block content %}

        <!-- My Account Start -->
        <div class="my-account">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-3">
                        <div class="nav flex-column nav-pills" role="tablist" aria-orientation="vertical">
                          <a class="nav-link" id="dashboard-nav" href="{% url 'user:profile' %}"><i class="fa fa-tachometer-alt"></i>Dashboard</a>
                          <a class="nav-link active" id="orders-nav" href="{% url 'product:orders' %}"><i class="fa fa-shopping-bag"></i>Orders</a>
                          <a class="nav-link" id="payment-nav" href="{% url 'user:payment' %}"><i class="fa fa-credit-card"></i>Payment Method</a>
                          <a class="nav-link" id="address-nav" href="{% url 'user:address' %}"><i class="fa fa-map-marker-alt"></i>Address</a>
                          <a class="nav-link" id="account-nav" href="{% url 'user:update_profile' %}"><i class="fa fa-user"></i>Update Details</a>
                          <a class="nav-link" href="{% url 'user:change_password' %}"><i class="fa fa-lock"></i>Change Password</a>
                          <a class="nav-link" href="{% url 'user:logout' %}" ><i class="fa fa-sign-out-alt"></i>Logout</a>
                        </div>
                    </div>
                    <div class="col-md-9">
                        <div class="tab-content">

                            <div class="tab-pane active" id="orders-tab" role="tabpanel" aria-labelledby="orders-nav">
                                <div class="table-responsive">
                                    <table class="table table-bordered">
                                        <thead class="thead-dark">
                                            <tr>
                                                <th>No</th>
                                                <th>Product</th>
                                                <th>Price</th>
                                                <th>Date</th>
                                                <th>Status</th>
                                                <th>Action</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                          {% for order in orders %}
                                            <tr>
                                                <td>{{ forloop.counter }}</td>
                                                <td>{{ order.product.title }}</td>
                                                <td>${{ order.product.discounted_price | multiply:order.quantity }}</td>
                                                <td>{{ order.created_at | date:"M d, Y" }}</td>
                                                <td><b>{{ order.status }}</b></td>
                                                <td><button class="btn">View</button></td>
                                            </tr>
                                          {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- My Account End -->

{% endblock %}

templates/payment.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

        <!-- My Account Start -->
        <div class="my-account">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-3">
                        <div class="nav flex-column nav-pills" role="tablist" aria-orientation="vertical">
                          <a class="nav-link" id="dashboard-nav" href="{% url 'user:profile' %}"><i class="fa fa-tachometer-alt"></i>Dashboard</a>
                          <a class="nav-link" id="orders-nav" href="{% url 'product:orders' %}"><i class="fa fa-shopping-bag"></i>Orders</a>
                          <a class="nav-link active" id="payment-nav" href="{% url 'user:payment' %}"><i class="fa fa-credit-card"></i>Payment Method</a>
                          <a class="nav-link" id="address-nav" href="{% url 'user:address' %}"><i class="fa fa-map-marker-alt"></i>Address</a>
                          <a class="nav-link" id="account-nav" href="{% url 'user:update_profile' %}"><i class="fa fa-user"></i>Update Details</a>
                          <a class="nav-link" href="{% url 'user:change_password' %}"><i class="fa fa-lock"></i>Change Password</a>
                          <a class="nav-link" href="{% url 'user:logout' %}" ><i class="fa fa-sign-out-alt"></i>Logout</a>
                        </div>
                    </div>
                    <div class="col-md-9">
                      <div class="tab-content">

                      <div class="tab-pane active" id="payment-tab" aria-labelledby="payment-nav">
                          <h4>Payment Method</h4>
                          <hr>
                          <p>
                              Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum quam ac mi viverra dictum.
                              In efficitur ipsum diam, at dignissim lorem tempor in. Vivamus tempor hendrerit finibus.
                              Nulla tristique viverra nisl, sit amet bibendum ante suscipit non.
                              Praesent in faucibus tellus, sed gravida lacus. Vivamus eu diam eros. Aliquam et sapien eget arcu rhoncus scelerisque.
                          </p>
                      </div>

                    </div>
                  </div>
                </div>
            </div>
        </div>
        <!-- My Account End -->

{% endblock %}

templates/register.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

        <!-- Login Start -->
        <div class="login">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-1"></div>
                    <div class="col-lg-6">
                        <div class="register-form">
                            <form method="post" class="row">
                                {% csrf_token %}
                                <div class="col-md-6">
                                    <label>First Name</label>
                                    <input class="form-control" name="first_name" type="text" placeholder="First Name">
                                </div>
                                <div class="col-md-6">
                                    <label>Last Name</label>
                                    <input class="form-control" name="last_name" type="text" placeholder="Last Name">
                                </div>
                                <div class="col-md-6">
                                    <label>Username</label>
                                    <input class="form-control" name="username" type="text" placeholder="Username">
                                </div>
                                <div class="col-md-6">
                                    <label>E-mail</label>
                                    <input class="form-control" name="email" type="email" placeholder="E-mail">
                                </div>
                                <div class="col-md-6">
                                    <label>Password</label>
                                    <input class="form-control" name="password" type="password" placeholder="Password">
                                </div>
                                <div class="col-md-6">
                                    <label>Confirm Password</label>
                                    <input class="form-control" name="confirm_password" type="password" placeholder="Password">
                                </div>
                                <div class="col-md-12">
                                    <button class="btn">Register</button>
                                </div>
                            </form>
                            <div class="login-register-link">Already have an account? <a href="{% url 'user:login' %}">Login here</a></div>
                        </div>
                    </div>
                    <div class="col-lg-5"></div>
                </div>
            </div>
        </div>
        <!-- Login End -->

{% endblock %}

templates/reset-password-done.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="row">
  <div class="col-md-3"></div>
  <div class="alert-message col-md-6">
    <p>An email with password reset link has been sent to you Email. Please refer to the email.</p>
  </div>
  <div class="col-md-3"></div>
</div>

{% endblock %}